#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/cygdrive/c/Users/gutha.3/Desktop/FPGA_Projects/QKD/qkd_transmitter/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'ram1', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'RAM1_'.
 * The prefix is the slave descriptor.
 */
#define RAM1_COMPONENT_TYPE altera_avalon_onchip_memory2
#define RAM1_COMPONENT_NAME ram1
#define RAM1_BASE 0x0
#define RAM1_SPAN 65536
#define RAM1_END 0xffff
#define RAM1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 1
#define RAM1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RAM1_CONTENTS_INFO ""
#define RAM1_DUAL_PORT 0
#define RAM1_GUI_RAM_BLOCK_TYPE AUTO
#define RAM1_INIT_CONTENTS_FILE soc_system_ram1
#define RAM1_INIT_MEM_CONTENT 0
#define RAM1_INSTANCE_ID RAM1
#define RAM1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RAM1_RAM_BLOCK_TYPE AUTO
#define RAM1_READ_DURING_WRITE_MODE DONT_CARE
#define RAM1_SINGLE_CLOCK_OP 0
#define RAM1_SIZE_MULTIPLE 1
#define RAM1_SIZE_VALUE 65536
#define RAM1_WRITABLE 1
#define RAM1_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define RAM1_MEMORY_INFO_GENERATE_DAT_SYM 1
#define RAM1_MEMORY_INFO_GENERATE_HEX 1
#define RAM1_MEMORY_INFO_HAS_BYTE_LANE 0
#define RAM1_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define RAM1_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define RAM1_MEMORY_INFO_MEM_INIT_FILENAME soc_system_ram1


#endif /* _ALTERA_HPS_0_H_ */
